### ISSUE TITLE
Backup with PrebackupPod doesn't work with k8up 2.6

### ISSUE THREAD

**Issue by TheBigLee** [k8up-io/k8up#822]
### Description

If you define a backup that uses a PreBackupPod, the actual backup job will never be created if there isn't a bound PVC in the namespace where the backup is running.

Once you create a Pod and a PVC, k8up will create the backup job and proceed as expected.
Furthermore, the created Job will only back up the PVC and not run the backup command from the PreBackupPd.

### Additional Context

This seems to have been introduced with the latest version of k8up (v2.6.0) and wasn't observed in the previous versions (2.5.3)

### Logs

Output of logs of the backupPod when using a PreBackupPod (only works if bound PVC is present):

```
2023-03-06T23:09:34Z	INFO	k8up	Starting k8up…	{"version": "2.6.0", "date": "2023-02-28T07:42:12Z", "commit": "6d8ab1d0c2bcfd3348e73b5298847c9641ca199e", "go_os": "linux", "go_arch": "amd64", "go_version": "go1.19.6", "uid": 65532, "gid": 0}
2023-03-06T23:09:34Z	INFO	k8up.restic	initializing
2023-03-06T23:09:34Z	INFO	k8up.restic	setting up a signal handler
2023-03-06T23:09:34Z	INFO	k8up.restic.restic	using the following restic options	{"options": [""]}
2023-03-06T23:09:34Z	INFO	k8up.restic.restic.RepoInit.command	restic command	{"path": "/usr/local/bin/restic", "args": ["init", "--option", ""]}
2023-03-06T23:09:34Z	INFO	k8up.restic.restic.RepoInit.command	Defining RESTIC_PROGRESS_FPS	{"frequency": 0.016666666666666666}
2023-03-06T23:09:34Z	INFO	k8up.restic.restic.unlock	unlocking repository	{"all": false}
2023-03-06T23:09:34Z	INFO	k8up.restic.restic.unlock.command	restic command	{"path": "/usr/local/bin/restic", "args": ["unlock", "--option", ""]}
2023-03-06T23:09:34Z	INFO	k8up.restic.restic.unlock.command	Defining RESTIC_PROGRESS_FPS	{"frequency": 0.016666666666666666}
2023-03-06T23:09:35Z	INFO	k8up.restic.restic.unlock.restic.stderr	successfully removed locks
2023-03-06T23:09:35Z	INFO	k8up.restic.restic.snapshots	getting list of snapshots
2023-03-06T23:09:35Z	INFO	k8up.restic.restic.snapshots.command	restic command	{"path": "/usr/local/bin/restic", "args": ["snapshots", "--option", "", "--json"]}
2023-03-06T23:09:35Z	INFO	k8up.restic.restic.snapshots.command	Defining RESTIC_PROGRESS_FPS	{"frequency": 0.016666666666666666}
2023-03-06T23:09:35Z	INFO	k8up.restic.k8sClient	listing all pods	{"annotation": "k8up.io/backupcommand", "namespace": "default"}
2023-03-06T23:09:35Z	INFO	k8up.restic	backups of annotated jobs have finished successfully
2023-03-06T23:09:35Z	INFO	k8up.restic.restic.backup	starting backup
2023-03-06T23:09:35Z	INFO	k8up.restic.restic.backup	starting backup for folder	{"foldername": "minio-pvc"}
2023-03-06T23:09:35Z	INFO	k8up.restic.restic.backup.command	restic command	{"path": "/usr/local/bin/restic", "args": ["backup", "--option", "", "--json", "--host", "default", "/data/minio-pvc"]}
2023-03-06T23:09:35Z	INFO	k8up.restic.restic.backup.command	Defining RESTIC_PROGRESS_FPS	{"frequency": 0.016666666666666666}
2023-03-06T23:09:36Z	INFO	k8up.restic.restic.backup.progress	progress of backup	{"percentage": "0.00%"}
2023-03-06T23:09:36Z	INFO	k8up.restic.restic.backup.progress	backup finished	{"new files": 12, "changed files": 4, "errors": 0}
2023-03-06T23:09:36Z	INFO	k8up.restic.restic.backup.progress	stats	{"time": 0.255726442, "bytes added": 97216, "bytes processed": 154300}
2023-03-06T23:09:36Z	INFO	k8up.restic.statsHandler.promStats	sending prometheus stats	{"url": "http://minio:9000"}
2023-03-06T23:09:36Z	ERROR	k8up.restic.restic	prometheus send failed	{"error": "unexpected status code 400 while pushing to http://minio:9000/metrics/job/restic_backup/instance/default: <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>BadRequest</Code><Message>An error occurred when parsing the HTTP request POST at &#39;/metrics/job/restic_backup/instance/default&#39;</Message><Resource>/metrics/job/restic_backup/instance/default</Resource><RequestId></RequestId><HostId></HostId></Error>"}
github.com/k8up-io/k8up/v2/restic/cli.(*Restic).sendBackupStats
	/home/runner/work/k8up/k8up/restic/cli/backup.go:95
github.com/k8up-io/k8up/v2/restic/logging.(*BackupOutputParser).out
	/home/runner/work/k8up/k8up/restic/logging/logging.go:162
github.com/k8up-io/k8up/v2/restic/logging.writer.Write
	/home/runner/work/k8up/k8up/restic/logging/logging.go:103
io.copyBuffer
	/opt/hostedtoolcache/go/1.19.6/x64/src/io/io.go:429
io.Copy
	/opt/hostedtoolcache/go/1.19.6/x64/src/io/io.go:386
os/exec.(*Cmd).writerDescriptor.func1
	/opt/hostedtoolcache/go/1.19.6/x64/src/os/exec/exec.go:407
os/exec.(*Cmd).Start.func1
	/opt/hostedtoolcache/go/1.19.6/x64/src/os/exec/exec.go:544
2023-03-06T23:09:36Z	INFO	k8up.restic.restic.backup	starting backup for folder	{"foldername": "test-pvc"}
2023-03-06T23:09:36Z	INFO	k8up.restic.restic.backup.command	restic command	{"path": "/usr/local/bin/restic", "args": ["backup", "--host", "default", "--json", "--option", "", "/data/test-pvc"]}
2023-03-06T23:09:36Z	INFO	k8up.restic.restic.backup.command	Defining RESTIC_PROGRESS_FPS	{"frequency": 0.016666666666666666}
2023-03-06T23:09:37Z	INFO	k8up.restic.restic.backup.progress	progress of backup	{"percentage": "0.00%"}
2023-03-06T23:09:37Z	INFO	k8up.restic.restic.backup.progress	backup finished	{"new files": 0, "changed files": 0, "errors": 0}
2023-03-06T23:09:37Z	INFO	k8up.restic.restic.backup.progress	stats	{"time": 0.247678861, "bytes added": 355, "bytes processed": 0}
2023-03-06T23:09:37Z	INFO	k8up.restic.statsHandler.promStats	sending prometheus stats	{"url": "http://minio:9000"}
2023-03-06T23:09:37Z	ERROR	k8up.restic.restic	prometheus send failed	{"error": "unexpected status code 400 while pushing to http://minio:9000/metrics/job/restic_backup/instance/default: <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>BadRequest</Code><Message>An error occurred when parsing the HTTP request POST at &#39;/metrics/job/restic_backup/instance/default&#39;</Message><Resource>/metrics/job/restic_backup/instance/default</Resource><RequestId></RequestId><HostId></HostId></Error>"}
github.com/k8up-io/k8up/v2/restic/cli.(*Restic).sendBackupStats
	/home/runner/work/k8up/k8up/restic/cli/backup.go:95
github.com/k8up-io/k8up/v2/restic/logging.(*BackupOutputParser).out
	/home/runner/work/k8up/k8up/restic/logging/logging.go:162
github.com/k8up-io/k8up/v2/restic/logging.writer.Write
	/home/runner/work/k8up/k8up/restic/logging/logging.go:103
io.copyBuffer
	/opt/hostedtoolcache/go/1.19.6/x64/src/io/io.go:429
io.Copy
	/opt/hostedtoolcache/go/1.19.6/x64/src/io/io.go:386
os/exec.(*Cmd).writerDescriptor.func1
	/opt/hostedtoolcache/go/1.19.6/x64/src/os/exec/exec.go:407
os/exec.(*Cmd).Start.func1
	/opt/hostedtoolcache/go/1.19.6/x64/src/os/exec/exec.go:544
2023-03-06T23:09:37Z	INFO	k8up.restic.restic.backup	backup finished, sending snapshot list
2023-03-06T23:09:37Z	INFO	k8up.restic.restic.snapshots	getting list of snapshots
2023-03-06T23:09:37Z	INFO	k8up.restic.restic.snapshots.command	restic command	{"path": "/usr/local/bin/restic", "args": ["snapshots", "--option", "", "--json"]}
2023-03-06T23:09:37Z	INFO	k8up.restic.restic.snapshots.command	Defining RESTIC_PROGRESS_FPS	{"frequency": 0.016666666666666666}

```

Output of logs of the backupPod when using a backupCommand annotation on the pod (only works if bound PVC is present):
```
k logs -f backup-backup-test-0-c589k
2023-03-07T08:40:49Z	INFO	k8up	Starting k8up…	{"version": "2.6.0", "date": "2023-02-28T07:42:12Z", "commit": "6d8ab1d0c2bcfd3348e73b5298847c9641ca199e", "go_os": "linux", "go_arch": "amd64", "go_version": "go1.19.6", "uid": 65532, "gid": 0}
2023-03-07T08:40:49Z	INFO	k8up.restic	initializing
2023-03-07T08:40:49Z	INFO	k8up.restic	setting up a signal handler
2023-03-07T08:40:49Z	INFO	k8up.restic.restic	using the following restic options	{"options": [""]}
2023-03-07T08:40:49Z	INFO	k8up.restic.restic.RepoInit.command	restic command	{"path": "/usr/local/bin/restic", "args": ["init", "--option", ""]}
2023-03-07T08:40:49Z	INFO	k8up.restic.restic.RepoInit.command	Defining RESTIC_PROGRESS_FPS	{"frequency": 0.016666666666666666}
2023-03-07T08:40:49Z	INFO	k8up.restic.restic.unlock	unlocking repository	{"all": false}
2023-03-07T08:40:49Z	INFO	k8up.restic.restic.unlock.command	restic command	{"path": "/usr/local/bin/restic", "args": ["unlock", "--option", ""]}
2023-03-07T08:40:49Z	INFO	k8up.restic.restic.unlock.command	Defining RESTIC_PROGRESS_FPS	{"frequency": 0.016666666666666666}
2023-03-07T08:40:49Z	INFO	k8up.restic.restic.unlock.restic.stderr	successfully removed locks
2023-03-07T08:40:49Z	INFO	k8up.restic.restic.snapshots	getting list of snapshots
2023-03-07T08:40:49Z	INFO	k8up.restic.restic.snapshots.command	restic command	{"path": "/usr/local/bin/restic", "args": ["snapshots", "--option", "", "--json"]}
2023-03-07T08:40:49Z	INFO	k8up.restic.restic.snapshots.command	Defining RESTIC_PROGRESS_FPS	{"frequency": 0.016666666666666666}
2023-03-07T08:40:50Z	INFO	k8up.restic.k8sClient	listing all pods	{"annotation": "k8up.io/backupcommand", "namespace": "default"}
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/k8up-io/k8up/v2/restic/kubernetes.(*PodLister).ListPods(0xc00031c180)
	/home/runner/work/k8up/k8up/restic/kubernetes/pod_list.go:93 +0x992
github.com/k8up-io/k8up/v2/cmd/restic.backupAnnotatedPods({0x1a3c300, 0xc000138000}, 0x1487b18?, {{0x1a3ed70?, 0xc000482f00?}, 0x0?})
	/home/runner/work/k8up/k8up/cmd/restic/main.go:249 +0x1ee
github.com/k8up-io/k8up/v2/cmd/restic.doBackup({0x1a3c300?, 0xc000138000?}, 0xc000482f00?, {{0x1a3ed70?, 0xc000482f00?}, 0xc000319560?})
	/home/runner/work/k8up/k8up/cmd/restic/main.go:226 +0x5f
github.com/k8up-io/k8up/v2/cmd/restic.run({0x1a3c300, 0xc000138000}, 0x1a3ed70?, {{0x1a3ed70?, 0xc000482f00?}, 0x1a2ae20?})
	/home/runner/work/k8up/k8up/cmd/restic/main.go:127 +0xbf
github.com/k8up-io/k8up/v2/cmd/restic.resticMain(0xc00004c3c0)
	/home/runner/work/k8up/k8up/cmd/restic/main.go:111 +0x2a7
github.com/urfave/cli/v2.(*Command).Run(0x258d320, 0xc00004c3c0, {0xc0004003b0, 0x1, 0x1})
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.23.7/command.go:271 +0xa42
github.com/urfave/cli/v2.(*Command).Run(0xc000670140, 0xc000523500, {0xc000134000, 0x2, 0x2})
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.23.7/command.go:264 +0xc97
github.com/urfave/cli/v2.(*App).RunContext(0xc00053a3c0, {0x1a3c300?, 0xc000138000}, {0xc000134000, 0x2, 0x2})
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.23.7/app.go:333 +0x665
github.com/urfave/cli/v2.(*App).Run(...)
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.23.7/app.go:310
main.main()
	/home/runner/work/k8up/k8up/cmd/k8up/main.go:29 +0x45
```

### Expected Behavior

K8up will run a backup job with PreBackupPods.

### Steps To Reproduce

1. Install kind and k8up:
```
kind create cluster --image=kindest/node:v1.23.13
kubectl apply -f https://github.com/k8up-io/k8up/releases/download/k8up-4.0.1/k8up-crd.yaml
helm repo add k8up-io https://k8up-io.github.io/k8up
helm repo update k8up-io
helm install k8up-io/k8up --generate-name --namespace k8up --create-namespace
```
2. Install Minio:
```
git clone https://github.com/k8up-io/k8up.git --depth=1
cd k8up/docs/modules/ROOT/examples/tutorial
kubectl apply -f secrets/backup-repo.yaml
kubectl apply -f secrets/minio-credentials.yaml
kubectl apply -k minio
```
3. Create a `PrebackupPod` and a `Backup`:
```
cat <<EOF | kubectl apply -f -
apiVersion: k8up.io/v1
kind: PreBackupPod
metadata:
  name: test-prebackup
spec:
  backupCommand: sh -c 'echo "foo bar"'
  pod:
    spec:
      containers:
        - image: busybox
          command:
            - 'sleep'
            - 'infinity'
          imagePullPolicy: Always
          name: prebackup-test
---
apiVersion: k8up.io/v1
kind: Backup
metadata:
  name: backup-test
spec:
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 2
  backend:
    repoPasswordSecretRef:
      name: backup-repo
      key: password
    s3:
      endpoint: http://minio:9000
      bucket: backups
      accessKeyIDSecretRef:
        name: minio-credentials
        key: username
      secretAccessKeySecretRef:
        name: minio-credentials
        key: password
EOF
```
4.  Wait for the pod defined in the PrebackupPod to start and check the status of the `Backup`:
```
kubectl get backup
NAME          SCHEDULE REF   COMPLETION   PREBACKUP   AGE
backup-test                               Ready       112s

kubectl describe backup
Name:         backup-test
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  k8up.io/v1
Kind:         Backup
Metadata:
  [...]
Spec:
  Backend:
    Repo Password Secret Ref:
      Key:   password
      Name:  backup-repo
    s3:
      Access Key ID Secret Ref:
        Key:     username
        Name:    minio-credentials
      Bucket:    backups
      Endpoint:  http://minio:9000
      Secret Access Key Secret Ref:
        Key:                      password
        Name:                     minio-credentials
  Failed Jobs History Limit:      2
  Prom URL:                       http://minio:9000
  Successful Jobs History Limit:  2
Status:
  Conditions:
    Last Transition Time:  2023-03-03T20:59:46Z
    Message:               The resource is ready
    Reason:                Ready
    Status:                True
    Type:                  PreBackupPodReady
Events:                    <none>

```
From now on, nothing will happen, and the backup will be stuck at this stage 
5. Create a simple Pod and PVC:
```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: test
      image: busybox
      command: ["echo", "Test Prebackup"]
      volumeMounts:
      - name: test
        mountPath: /test
  restartPolicy: Never
  volumes:
  - name: test
    persistentVolumeClaim:
      claimName: test-pvc

EOF
```

Or when not using a `PreBackupPod`:

```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  annotations:
    k8up.io/backupcommand: sh -c 'echo "foo bar"'
spec:
  containers:
    - name: test
      image: busybox
      command: ["sleep", "100000"]
      volumeMounts:
      - name: test
        mountPath: /test
  restartPolicy: Never
  volumes:
  - name: test
    persistentVolumeClaim:
      claimName: test-pvc
EOF
```

6. Now a job is actually created for the backup (the backup pod will fail to start due to missing secrets) However, if the secrets are present, the job will not run the backup command for the PreBackupPod
```
kubectl get jobs
NAME                   COMPLETIONS   DURATION   AGE
backup-backup-test-0   0/1           2m36s      2m36s

kubectl describe backup
Name:         backup-test
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  k8up.io/v1
Kind:         Backup
Metadata:
  [...]
Spec:
  Backend:
    Repo Password Secret Ref:
      Key:   password
      Name:  backup-repo
    s3:
      Access Key ID Secret Ref:
        Key:     username
        Name:    minio-credentials
      Bucket:    backups
      Endpoint:  http://minio:9000
      Secret Access Key Secret Ref:
        Key:                      password
        Name:                     minio-credentials
  Failed Jobs History Limit:      2
  Prom URL:                       http://minio:9000
  Successful Jobs History Limit:  2
Status:
  Conditions:
    Last Transition Time:  2023-03-03T20:59:46Z
    Message:               The resource is ready
    Reason:                Ready
    Status:                True
    Type:                  PreBackupPodReady
    Last Transition Time:  2023-03-03T21:15:46Z
    Message:               "backup_backup-test" has 0 succeeded, 0 failed, and 1 started jobs
    Reason:                Ready
    Status:                True
    Type:                  Ready
    Last Transition Time:  2023-03-03T21:15:46Z
    Message:               The job is progressing
    Reason:                Started
    Status:                True
    Type:                  Progressing
  Started:                 true
Events:                    <none>
```
7. 

### Version of K8up

v2.6.0

### Version of Kubernetes

1.23.13

### Distribution of Kubernetes

k3s, kind

**Comment by Kidswiss** [comment]
@TheBigLee can you please also attach the log of the backup pod as well? Thanks

**Comment by Kidswiss** [comment]
Did a bit more debugging... Looks like since the last change we create the prebackuppods with a camel-cased `k8up.io/preBackupPod` annotation, and the listing and filtering will only look for lower cased ones.

https://github.com/k8up-io/k8up/blob/master/operator/backupcontroller/prebackup_utils.go#L46

We should probably re-use the `BACKUP_BACKUPCOMMANDANNOTATION` value for this or users could end-up with non-working prebackuppods if they set this annotation to a different value.
